apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-reviews2-api-deployment
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: shop-reviews2-api
      version: v2
  template:
    metadata:
      labels:
        app: shop-reviews2-api
        version: v2
    spec:
      containers:
      - name: shop-reviews2-api-container
        image: rosinebelle/espresso-shop-reviews
        ports:
        - containerPort: 80
        env:
        - name: SERVICE_VERSION
          value: v2
        - name: POSTGRES_HOST
          value: postgres-repmgr-service
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: espresso-shop-reviews-svc
spec:
  selector:
    app: shop-reviews2-api
    version: v2
  ports:
    - protocol: TCP
      port: 8092
      targetPort: 80

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: shop-reviews2-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shop-reviews2-api-deployment
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shop-reviews2-api-service-account

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: shop-reviews2-api-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: shop-reviews2-api

