apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-reviews1-api-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: shop-reviews1-api
      version: v1
  template:
    metadata:
      labels:
        app: shop-reviews1-api
        version: v1
    spec:
      containers:
      - name: shop-reviews1-api-container
        image: rosinebelle/espresso-shop-reviews
        ports:
        - containerPort: 80
        env:
        - name: SERVICE_VERSION
          value: v1

---
apiVersion: v1
kind: Service
metadata:
  name: espresso-shop-reviews-svc
spec:
  selector:
    app: shop-reviews1-api
    version: v1
  ports:
    - protocol: TCP
      port: 8092
      targetPort: 80

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: shop-reviews1-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shop-reviews1-api-deployment
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shop-reviews1-api-service-account

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: shop-reviews1-api-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: shop-reviews1-api
